# This file deploys to Firebase Hosting only upon release creation

name: Deploy to Firebase Hosting on Release
on:
  release:
    types: [created] 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ETECHLEAP }}'
          channelId: live  
          projectId: etechleap 
